!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! ISO_C_BINDING interface to OpenSHMEM.
!
! John C. Linford (jlinford@paratools.com)
!
! This file was automatically generated by the TAU Performance System using the 
! "cowboy code" version of tau_wrap.cpp available at
! https://github.com/jlinford/shmem_iso_c_binding
!
!
! Copyright (c) 2017, ParaTools, Inc.
! All rights reserved.
!
! Redistribution and use in source and binary forms, with or without
! modification, are permitted provided that the following conditions are met:
! (1) Redistributions of source code must retain the above copyright notice,
!     this list of conditions and the following disclaimer.
! (2) Redistributions in binary form must reproduce the above copyright notice,
!     this list of conditions and the following disclaimer in the documentation
!     and/or other materials provided with the distribution.
! (3) Neither the name of ParaTools, Inc. nor the names of its contributors may
!     be used to endorse or promote products derived from this software without
!     specific prior written permission.
!
! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
! AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
! IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
! DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
! FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
! DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
! SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
! CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
! OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
! OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


module shmem
  implicit none

  interface
    subroutine start_pes(npes) &
        bind(C,name="start_pes")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT), value :: npes
    end subroutine start_pes
  end interface

  interface
    subroutine shmem_init() &
        bind(C,name="shmem_init")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_init
  end interface

  interface
    subroutine shmem_finalize() &
        bind(C,name="shmem_finalize")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_finalize
  end interface

  interface
    subroutine shmem_global_exit(status) &
        bind(C,name="shmem_global_exit")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT), value :: status
    end subroutine shmem_global_exit
  end interface

  interface
    integer(kind=C_INT) function shmem_my_pe() &
        bind(C,name="shmem_my_pe")
      use, intrinsic :: iso_c_binding
    end function shmem_my_pe
  end interface

  interface
    integer(kind=C_INT) function shmem_n_pes() &
        bind(C,name="shmem_n_pes")
      use, intrinsic :: iso_c_binding
    end function shmem_n_pes
  end interface

  interface
    subroutine shmem_short_put(dest, src, nelems, pe) &
        bind(C,name="shmem_short_put")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: dest
      integer(kind=C_SHORT) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_put
  end interface

  interface
    subroutine shmem_char_put(dest, src, nelems, pe) &
        bind(C,name="shmem_char_put")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: dest
      character(kind=C_CHAR) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_put
  end interface

  interface
    subroutine shmem_int_put(dest, src, nelems, pe) &
        bind(C,name="shmem_int_put")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: dest
      integer(kind=C_INT) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_put
  end interface

  interface
    subroutine shmem_long_put(dest, src, nelems, pe) &
        bind(C,name="shmem_long_put")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: dest
      integer(kind=C_LONG) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_put
  end interface

  interface
    subroutine shmem_longlong_put(dest, src, nelems, pe) &
        bind(C,name="shmem_longlong_put")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: dest
      integer(kind=C_LONG_LONG) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_put
  end interface

  interface
    subroutine shmem_longdouble_put(dest, src, nelems, pe) &
        bind(C,name="shmem_longdouble_put")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: dest
      real(kind=C_LONG_DOUBLE) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_put
  end interface

  interface
    subroutine shmem_double_put(dest, src, nelems, pe) &
        bind(C,name="shmem_double_put")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: dest
      real(kind=C_DOUBLE) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_put
  end interface

  interface
    subroutine shmem_float_put(dest, src, nelems, pe) &
        bind(C,name="shmem_float_put")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: dest
      real(kind=C_FLOAT) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_put
  end interface

  interface
    subroutine shmem_putmem(dest, src, nelems, pe) &
        bind(C,name="shmem_putmem")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_putmem
  end interface

  interface
    subroutine shmem_put32(dest, src, nelems, pe) &
        bind(C,name="shmem_put32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_put32
  end interface

  interface
    subroutine shmem_put64(dest, src, nelems, pe) &
        bind(C,name="shmem_put64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_put64
  end interface

  interface
    subroutine shmem_put128(dest, src, nelems, pe) &
        bind(C,name="shmem_put128")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_put128
  end interface

  interface
    subroutine shmem_short_get(dest, src, nelems, pe) &
        bind(C,name="shmem_short_get")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: dest
      integer(kind=C_SHORT) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_get
  end interface

  interface
    subroutine shmem_int_get(dest, src, nelems, pe) &
        bind(C,name="shmem_int_get")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: dest
      integer(kind=C_INT) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_get
  end interface

  interface
    subroutine shmem_char_get(dest, src, nelems, pe) &
        bind(C,name="shmem_char_get")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: dest
      character(kind=C_CHAR) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_get
  end interface

  interface
    subroutine shmem_long_get(dest, src, nelems, pe) &
        bind(C,name="shmem_long_get")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: dest
      integer(kind=C_LONG) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_get
  end interface

  interface
    subroutine shmem_longlong_get(dest, src, nelems, pe) &
        bind(C,name="shmem_longlong_get")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: dest
      integer(kind=C_LONG_LONG) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_get
  end interface

  interface
    subroutine shmem_longdouble_get(dest, src, nelems, pe) &
        bind(C,name="shmem_longdouble_get")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: dest
      real(kind=C_LONG_DOUBLE) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_get
  end interface

  interface
    subroutine shmem_double_get(dest, src, nelems, pe) &
        bind(C,name="shmem_double_get")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: dest
      real(kind=C_DOUBLE) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_get
  end interface

  interface
    subroutine shmem_float_get(dest, src, nelems, pe) &
        bind(C,name="shmem_float_get")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: dest
      real(kind=C_FLOAT) :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_get
  end interface

  interface
    subroutine shmem_getmem(dest, src, nelems, pe) &
        bind(C,name="shmem_getmem")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_getmem
  end interface

  interface
    subroutine shmem_get32(dest, src, nelems, pe) &
        bind(C,name="shmem_get32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_get32
  end interface

  interface
    subroutine shmem_get64(dest, src, nelems, pe) &
        bind(C,name="shmem_get64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_get64
  end interface

  interface
    subroutine shmem_get128(dest, src, nelems, pe) &
        bind(C,name="shmem_get128")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: src
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_get128
  end interface

  interface
    subroutine shmem_char_p(addr, value, pe) &
        bind(C,name="shmem_char_p")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: addr
      character(kind=C_CHAR), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_p
  end interface

  interface
    subroutine shmem_short_p(addr, value, pe) &
        bind(C,name="shmem_short_p")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: addr
      integer(kind=C_SHORT), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_p
  end interface

  interface
    subroutine shmem_int_p(addr, value, pe) &
        bind(C,name="shmem_int_p")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: addr
      integer(kind=C_INT), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_p
  end interface

  interface
    subroutine shmem_long_p(addr, value, pe) &
        bind(C,name="shmem_long_p")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: addr
      integer(kind=C_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_p
  end interface

  interface
    subroutine shmem_longlong_p(addr, value, pe) &
        bind(C,name="shmem_longlong_p")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: addr
      integer(kind=C_LONG_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_p
  end interface

  interface
    subroutine shmem_float_p(addr, value, pe) &
        bind(C,name="shmem_float_p")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: addr
      real(kind=C_FLOAT), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_p
  end interface

  interface
    subroutine shmem_double_p(addr, value, pe) &
        bind(C,name="shmem_double_p")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: addr
      real(kind=C_DOUBLE), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_p
  end interface

  interface
    subroutine shmem_longdouble_p(addr, value, pe) &
        bind(C,name="shmem_longdouble_p")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: addr
      real(kind=C_LONG_DOUBLE), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_p
  end interface

  interface
    character(kind=C_CHAR) function shmem_char_g(addr, pe) &
        bind(C,name="shmem_char_g")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_char_g
  end interface

  interface
    integer(kind=C_SHORT) function shmem_short_g(addr, pe) &
        bind(C,name="shmem_short_g")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_short_g
  end interface

  interface
    integer(kind=C_INT) function shmem_int_g(addr, pe) &
        bind(C,name="shmem_int_g")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_int_g
  end interface

  interface
    integer(kind=C_LONG) function shmem_long_g(addr, pe) &
        bind(C,name="shmem_long_g")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_long_g
  end interface

  interface
    integer(kind=C_LONG_LONG) function shmem_longlong_g(addr, pe) &
        bind(C,name="shmem_longlong_g")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_longlong_g
  end interface

  interface
    real(kind=C_FLOAT) function shmem_float_g(addr, pe) &
        bind(C,name="shmem_float_g")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_float_g
  end interface

  interface
    real(kind=C_DOUBLE) function shmem_double_g(addr, pe) &
        bind(C,name="shmem_double_g")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_double_g
  end interface

  interface
    real(kind=C_LONG_DOUBLE) function shmem_longdouble_g(addr, pe) &
        bind(C,name="shmem_longdouble_g")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_longdouble_g
  end interface

  interface
    subroutine shmem_double_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_double_iput")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_iput
  end interface

  interface
    subroutine shmem_float_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_float_iput")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_iput
  end interface

  interface
    subroutine shmem_int_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_int_iput")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_iput
  end interface

  interface
    subroutine shmem_char_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_char_iput")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: target
      character(kind=C_CHAR) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_iput
  end interface

  interface
    subroutine shmem_iput32(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_iput32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_iput32
  end interface

  interface
    subroutine shmem_iput64(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_iput64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_iput64
  end interface

  interface
    subroutine shmem_iput128(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_iput128")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_iput128
  end interface

  interface
    subroutine shmem_long_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_long_iput")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_iput
  end interface

  interface
    subroutine shmem_longdouble_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_longdouble_iput")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: target
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_iput
  end interface

  interface
    subroutine shmem_longlong_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_longlong_iput")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_iput
  end interface

  interface
    subroutine shmem_short_iput(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_short_iput")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_iput
  end interface

  interface
    subroutine shmem_double_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_double_iget")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_iget
  end interface

  interface
    subroutine shmem_float_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_float_iget")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_iget
  end interface

  interface
    subroutine shmem_int_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_int_iget")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_iget
  end interface

  interface
    subroutine shmem_char_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_char_iget")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: target
      character(kind=C_CHAR) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_iget
  end interface

  interface
    subroutine shmem_iget32(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_iget32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_iget32
  end interface

  interface
    subroutine shmem_iget64(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_iget64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_iget64
  end interface

  interface
    subroutine shmem_iget128(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_iget128")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_iget128
  end interface

  interface
    subroutine shmem_long_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_long_iget")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_iget
  end interface

  interface
    subroutine shmem_longdouble_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_longdouble_iget")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: target
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_iget
  end interface

  interface
    subroutine shmem_longlong_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_longlong_iget")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_iget
  end interface

  interface
    subroutine shmem_short_iget(target, source, tst, sst, nelems, pe) &
        bind(C,name="shmem_short_iget")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INTPTR_T), value :: tst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_iget
  end interface

  interface
    subroutine shmem_double_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_double_put_nbi")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: dest
      real(kind=C_DOUBLE) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_put_nbi
  end interface

  interface
    subroutine shmem_float_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_float_put_nbi")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: dest
      real(kind=C_FLOAT) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_put_nbi
  end interface

  interface
    subroutine shmem_char_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_char_put_nbi")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: dest
      character(kind=C_CHAR) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_put_nbi
  end interface

  interface
    subroutine shmem_int_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_int_put_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: dest
      integer(kind=C_INT) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_put_nbi
  end interface

  interface
    subroutine shmem_long_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_long_put_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: dest
      integer(kind=C_LONG) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_put_nbi
  end interface

  interface
    subroutine shmem_longdouble_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_longdouble_put_nbi")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: dest
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_put_nbi
  end interface

  interface
    subroutine shmem_longlong_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_longlong_put_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: dest
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_put_nbi
  end interface

  interface
    subroutine shmem_put32_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_put32_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_put32_nbi
  end interface

  interface
    subroutine shmem_put64_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_put64_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_put64_nbi
  end interface

  interface
    subroutine shmem_put128_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_put128_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_put128_nbi
  end interface

  interface
    subroutine shmem_putmem_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_putmem_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_putmem_nbi
  end interface

  interface
    subroutine shmem_short_put_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_short_put_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: dest
      integer(kind=C_SHORT) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_put_nbi
  end interface

  interface
    subroutine shmem_double_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_double_get_nbi")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: dest
      real(kind=C_DOUBLE) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_get_nbi
  end interface

  interface
    subroutine shmem_float_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_float_get_nbi")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: dest
      real(kind=C_FLOAT) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_get_nbi
  end interface

  interface
    subroutine shmem_get32_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_get32_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_get32_nbi
  end interface

  interface
    subroutine shmem_get64_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_get64_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_get64_nbi
  end interface

  interface
    subroutine shmem_get128_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_get128_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_get128_nbi
  end interface

  interface
    subroutine shmem_getmem_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_getmem_nbi")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: dest
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_getmem_nbi
  end interface

  interface
    subroutine shmem_int_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_int_get_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: dest
      integer(kind=C_INT) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_get_nbi
  end interface

  interface
    subroutine shmem_char_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_char_get_nbi")
      use, intrinsic :: iso_c_binding
      character(kind=C_CHAR) :: dest
      character(kind=C_CHAR) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_char_get_nbi
  end interface

  interface
    subroutine shmem_long_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_long_get_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: dest
      integer(kind=C_LONG) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_get_nbi
  end interface

  interface
    subroutine shmem_longdouble_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_longdouble_get_nbi")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: dest
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longdouble_get_nbi
  end interface

  interface
    subroutine shmem_longlong_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_longlong_get_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: dest
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_get_nbi
  end interface

  interface
    subroutine shmem_short_get_nbi(dest, source, nelems, pe) &
        bind(C,name="shmem_short_get_nbi")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: dest
      integer(kind=C_SHORT) :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: pe
    end subroutine shmem_short_get_nbi
  end interface

  interface
    subroutine shmem_barrier_all() &
        bind(C,name="shmem_barrier_all")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_barrier_all
  end interface

  interface
    subroutine shmem_barrier(PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_barrier")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_barrier
  end interface

  interface
    subroutine shmem_fence() &
        bind(C,name="shmem_fence")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_fence
  end interface

  interface
    subroutine shmem_quiet() &
        bind(C,name="shmem_quiet")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_quiet
  end interface

  interface
    integer(kind=C_INT) function shmem_pe_accessible(pe) &
        bind(C,name="shmem_pe_accessible")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT), value :: pe
    end function shmem_pe_accessible
  end interface

  interface
    integer(kind=C_INT) function shmem_addr_accessible(addr, pe) &
        bind(C,name="shmem_addr_accessible")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: addr
      integer(kind=C_INT), value :: pe
    end function shmem_addr_accessible
  end interface

  interface
    type(C_PTR) function shmem_ptr(target, pe) &
        bind(C,name="shmem_ptr")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      integer(kind=C_INT), value :: pe
    end function shmem_ptr
  end interface

  interface
    type(C_PTR) function shmalloc(size) &
        bind(C,name="shmalloc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SIZE_T), value :: size
    end function shmalloc
  end interface

  interface
    subroutine shfree(ptr) &
        bind(C,name="shfree")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: ptr
    end subroutine shfree
  end interface

  interface
    type(C_PTR) function shrealloc(ptr, size) &
        bind(C,name="shrealloc")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: ptr
      integer(kind=C_SIZE_T), value :: size
    end function shrealloc
  end interface

  interface
    type(C_PTR) function shmemalign(alignment, size) &
        bind(C,name="shmemalign")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SIZE_T), value :: alignment
      integer(kind=C_SIZE_T), value :: size
    end function shmemalign
  end interface

  interface
    type(C_PTR) function shmem_malloc(size) &
        bind(C,name="shmem_malloc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SIZE_T), value :: size
    end function shmem_malloc
  end interface

  interface
    subroutine shmem_free(ptr) &
        bind(C,name="shmem_free")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: ptr
    end subroutine shmem_free
  end interface

  interface
    type(C_PTR) function shmem_realloc(ptr, size) &
        bind(C,name="shmem_realloc")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: ptr
      integer(kind=C_SIZE_T), value :: size
    end function shmem_realloc
  end interface

  interface
    type(C_PTR) function shmem_align(alignment, size) &
        bind(C,name="shmem_align")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SIZE_T), value :: alignment
      integer(kind=C_SIZE_T), value :: size
    end function shmem_align
  end interface

  interface
    subroutine shmem_long_wait_until(ivar, cmp, cmp_value) &
        bind(C,name="shmem_long_wait_until")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: ivar
      integer(kind=C_INT), value :: cmp
      integer(kind=C_LONG), value :: cmp_value
    end subroutine shmem_long_wait_until
  end interface

  interface
    subroutine shmem_short_wait_until(ivar, cmp, cmp_value) &
        bind(C,name="shmem_short_wait_until")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: ivar
      integer(kind=C_INT), value :: cmp
      integer(kind=C_SHORT), value :: cmp_value
    end subroutine shmem_short_wait_until
  end interface

  interface
    subroutine shmem_int_wait_until(ivar, cmp, cmp_value) &
        bind(C,name="shmem_int_wait_until")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: ivar
      integer(kind=C_INT), value :: cmp
      integer(kind=C_INT), value :: cmp_value
    end subroutine shmem_int_wait_until
  end interface

  interface
    subroutine shmem_longlong_wait_until(ivar, cmp, cmp_value) &
        bind(C,name="shmem_longlong_wait_until")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: ivar
      integer(kind=C_INT), value :: cmp
      integer(kind=C_LONG_LONG), value :: cmp_value
    end subroutine shmem_longlong_wait_until
  end interface

  interface
    subroutine shmem_long_wait(ivar, cmp_value) &
        bind(C,name="shmem_long_wait")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: ivar
      integer(kind=C_LONG), value :: cmp_value
    end subroutine shmem_long_wait
  end interface

  interface
    subroutine shmem_short_wait(ivar, cmp_value) &
        bind(C,name="shmem_short_wait")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: ivar
      integer(kind=C_SHORT), value :: cmp_value
    end subroutine shmem_short_wait
  end interface

  interface
    subroutine shmem_int_wait(ivar, cmp_value) &
        bind(C,name="shmem_int_wait")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: ivar
      integer(kind=C_INT), value :: cmp_value
    end subroutine shmem_int_wait
  end interface

  interface
    subroutine shmem_longlong_wait(ivar, cmp_value) &
        bind(C,name="shmem_longlong_wait")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: ivar
      integer(kind=C_LONG_LONG), value :: cmp_value
    end subroutine shmem_longlong_wait
  end interface

  interface
    integer(kind=C_LONG) function shmem_long_swap(target, value, pe) &
        bind(C,name="shmem_long_swap")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_long_swap
  end interface

  interface
    integer(kind=C_INT) function shmem_int_swap(target, value, pe) &
        bind(C,name="shmem_int_swap")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_int_swap
  end interface

  interface
    integer(kind=C_LONG_LONG) function shmem_longlong_swap(target, value, pe) &
        bind(C,name="shmem_longlong_swap")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_longlong_swap
  end interface

  interface
    real(kind=C_FLOAT) function shmem_float_swap(target, value, pe) &
        bind(C,name="shmem_float_swap")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_float_swap
  end interface

  interface
    real(kind=C_DOUBLE) function shmem_double_swap(target, value, pe) &
        bind(C,name="shmem_double_swap")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_double_swap
  end interface

  interface
    integer(kind=C_LONG) function shmem_long_cswap(target, cond, value, pe) &
        bind(C,name="shmem_long_cswap")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG), value :: cond
      integer(kind=C_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_long_cswap
  end interface

  interface
    integer(kind=C_INT) function shmem_int_cswap(target, cond, value, pe) &
        bind(C,name="shmem_int_cswap")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT), value :: cond
      integer(kind=C_INT), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_int_cswap
  end interface

  interface
    integer(kind=C_LONG_LONG) function shmem_longlong_cswap(target, cond, value, pe) &
        bind(C,name="shmem_longlong_cswap")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG), value :: cond
      integer(kind=C_LONG_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_longlong_cswap
  end interface

  interface
    integer(kind=C_LONG) function shmem_long_fadd(target, value, pe) &
        bind(C,name="shmem_long_fadd")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_long_fadd
  end interface

  interface
    integer(kind=C_INT) function shmem_int_fadd(target, value, pe) &
        bind(C,name="shmem_int_fadd")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_int_fadd
  end interface

  interface
    integer(kind=C_LONG_LONG) function shmem_longlong_fadd(target, value, pe) &
        bind(C,name="shmem_longlong_fadd")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end function shmem_longlong_fadd
  end interface

  interface
    integer(kind=C_LONG) function shmem_long_finc(target, pe) &
        bind(C,name="shmem_long_finc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_INT), value :: pe
    end function shmem_long_finc
  end interface

  interface
    integer(kind=C_INT) function shmem_int_finc(target, pe) &
        bind(C,name="shmem_int_finc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT), value :: pe
    end function shmem_int_finc
  end interface

  interface
    integer(kind=C_LONG_LONG) function shmem_longlong_finc(target, pe) &
        bind(C,name="shmem_longlong_finc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_INT), value :: pe
    end function shmem_longlong_finc
  end interface

  interface
    subroutine shmem_long_add(target, value, pe) &
        bind(C,name="shmem_long_add")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_add
  end interface

  interface
    subroutine shmem_int_add(target, value, pe) &
        bind(C,name="shmem_int_add")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_add
  end interface

  interface
    subroutine shmem_longlong_add(target, value, pe) &
        bind(C,name="shmem_longlong_add")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_add
  end interface

  interface
    subroutine shmem_long_inc(target, pe) &
        bind(C,name="shmem_long_inc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_inc
  end interface

  interface
    subroutine shmem_int_inc(target, pe) &
        bind(C,name="shmem_int_inc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_inc
  end interface

  interface
    subroutine shmem_longlong_inc(target, pe) &
        bind(C,name="shmem_longlong_inc")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_inc
  end interface

  interface
    subroutine shmem_clear_cache_inv() &
        bind(C,name="shmem_clear_cache_inv")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_clear_cache_inv
  end interface

  interface
    subroutine shmem_set_cache_inv() &
        bind(C,name="shmem_set_cache_inv")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_set_cache_inv
  end interface

  interface
    subroutine shmem_clear_cache_line_inv(target) &
        bind(C,name="shmem_clear_cache_line_inv")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
    end subroutine shmem_clear_cache_line_inv
  end interface

  interface
    subroutine shmem_set_cache_line_inv(target) &
        bind(C,name="shmem_set_cache_line_inv")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
    end subroutine shmem_set_cache_line_inv
  end interface

  interface
    subroutine shmem_udcflush() &
        bind(C,name="shmem_udcflush")
      use, intrinsic :: iso_c_binding
    end subroutine shmem_udcflush
  end interface

  interface
    subroutine shmem_udcflush_line(target) &
        bind(C,name="shmem_udcflush_line")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
    end subroutine shmem_udcflush_line
  end interface

  interface
    subroutine shmem_long_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_sum_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_sum_to_all
  end interface

  interface
    subroutine shmem_double_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_double_sum_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_double_sum_to_all
  end interface

  interface
    subroutine shmem_float_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_float_sum_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_FLOAT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_float_sum_to_all
  end interface

  interface
    subroutine shmem_int_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_sum_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_sum_to_all
  end interface

  interface
    subroutine shmem_longdouble_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longdouble_sum_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: target
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_LONG_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longdouble_sum_to_all
  end interface

  interface
    subroutine shmem_longlong_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_sum_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_sum_to_all
  end interface

  interface
    subroutine shmem_short_sum_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_sum_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_sum_to_all
  end interface

  interface
    subroutine shmem_double_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_double_prod_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_double_prod_to_all
  end interface

  interface
    subroutine shmem_float_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_float_prod_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_FLOAT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_float_prod_to_all
  end interface

  interface
    subroutine shmem_int_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_prod_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_prod_to_all
  end interface

  interface
    subroutine shmem_long_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_prod_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_prod_to_all
  end interface

  interface
    subroutine shmem_longdouble_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longdouble_prod_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: target
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_LONG_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longdouble_prod_to_all
  end interface

  interface
    subroutine shmem_longlong_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_prod_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_prod_to_all
  end interface

  interface
    subroutine shmem_short_prod_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_prod_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_prod_to_all
  end interface

  interface
    subroutine shmem_int_and_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_and_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_and_to_all
  end interface

  interface
    subroutine shmem_long_and_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_and_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_and_to_all
  end interface

  interface
    subroutine shmem_longlong_and_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_and_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_and_to_all
  end interface

  interface
    subroutine shmem_short_and_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_and_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_and_to_all
  end interface

  interface
    subroutine shmem_int_or_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_or_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_or_to_all
  end interface

  interface
    subroutine shmem_long_or_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_or_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_or_to_all
  end interface

  interface
    subroutine shmem_longlong_or_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_or_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_or_to_all
  end interface

  interface
    subroutine shmem_short_or_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_or_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_or_to_all
  end interface

  interface
    subroutine shmem_int_xor_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_xor_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_xor_to_all
  end interface

  interface
    subroutine shmem_long_xor_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_xor_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_xor_to_all
  end interface

  interface
    subroutine shmem_longlong_xor_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_xor_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_xor_to_all
  end interface

  interface
    subroutine shmem_short_xor_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_xor_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_xor_to_all
  end interface

  interface
    subroutine shmem_int_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_max_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_max_to_all
  end interface

  interface
    subroutine shmem_long_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_max_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_max_to_all
  end interface

  interface
    subroutine shmem_longlong_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_max_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_max_to_all
  end interface

  interface
    subroutine shmem_short_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_max_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_max_to_all
  end interface

  interface
    subroutine shmem_longdouble_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longdouble_max_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: target
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_LONG_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longdouble_max_to_all
  end interface

  interface
    subroutine shmem_float_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_float_max_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_FLOAT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_float_max_to_all
  end interface

  interface
    subroutine shmem_double_max_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_double_max_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_double_max_to_all
  end interface

  interface
    subroutine shmem_int_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_int_min_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: target
      integer(kind=C_INT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_INT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_int_min_to_all
  end interface

  interface
    subroutine shmem_long_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_long_min_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: target
      integer(kind=C_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_long_min_to_all
  end interface

  interface
    subroutine shmem_longlong_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longlong_min_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: target
      integer(kind=C_LONG_LONG) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG_LONG) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longlong_min_to_all
  end interface

  interface
    subroutine shmem_short_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_short_min_to_all")
      use, intrinsic :: iso_c_binding
      integer(kind=C_SHORT) :: target
      integer(kind=C_SHORT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_SHORT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_short_min_to_all
  end interface

  interface
    subroutine shmem_longdouble_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_longdouble_min_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_LONG_DOUBLE) :: target
      real(kind=C_LONG_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_LONG_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_longdouble_min_to_all
  end interface

  interface
    subroutine shmem_float_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_float_min_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: target
      real(kind=C_FLOAT) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_FLOAT) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_float_min_to_all
  end interface

  interface
    subroutine shmem_double_min_to_all(target, source, nreduce, PE_start, logPE_stride, PE_size, pWrk, pSync) &
        bind(C,name="shmem_double_min_to_all")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: target
      real(kind=C_DOUBLE) :: source
      integer(kind=C_INT), value :: nreduce
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      real(kind=C_DOUBLE) :: pWrk
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_double_min_to_all
  end interface

  interface
    subroutine shmem_broadcast64(target, source, nelems, PE_root, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_broadcast64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_root
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_broadcast64
  end interface

  interface
    subroutine shmem_broadcast32(target, source, nelems, PE_root, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_broadcast32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_root
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_broadcast32
  end interface

  interface
    subroutine shmem_fcollect64(target, source, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_fcollect64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_fcollect64
  end interface

  interface
    subroutine shmem_fcollect32(target, source, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_fcollect32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_fcollect32
  end interface

  interface
    subroutine shmem_collect64(target, source, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_collect64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_collect64
  end interface

  interface
    subroutine shmem_collect32(target, source, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_collect32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_collect32
  end interface

  interface
    subroutine shmem_alltoall32(target, source, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_alltoall32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_alltoall32
  end interface

  interface
    subroutine shmem_alltoall64(target, source, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_alltoall64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_alltoall64
  end interface

  interface
    subroutine shmem_alltoalls32(target, source, dst, sst, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_alltoalls32")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: dst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_alltoalls32
  end interface

  interface
    subroutine shmem_alltoalls64(target, source, dst, sst, nelems, PE_start, logPE_stride, PE_size, pSync) &
        bind(C,name="shmem_alltoalls64")
      use, intrinsic :: iso_c_binding
      type(C_PTR), value :: target
      type(C_PTR), value :: source
      integer(kind=C_INTPTR_T), value :: dst
      integer(kind=C_INTPTR_T), value :: sst
      integer(kind=C_SIZE_T), value :: nelems
      integer(kind=C_INT), value :: PE_start
      integer(kind=C_INT), value :: logPE_stride
      integer(kind=C_INT), value :: PE_size
      integer(kind=C_LONG) :: pSync
    end subroutine shmem_alltoalls64
  end interface

  interface
    subroutine shmem_set_lock(lock) &
        bind(C,name="shmem_set_lock")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: lock
    end subroutine shmem_set_lock
  end interface

  interface
    subroutine shmem_clear_lock(lock) &
        bind(C,name="shmem_clear_lock")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: lock
    end subroutine shmem_clear_lock
  end interface

  interface
    integer(kind=C_INT) function shmem_test_lock(lock) &
        bind(C,name="shmem_test_lock")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: lock
    end function shmem_test_lock
  end interface

  interface
    integer(kind=C_INT) function shmem_int_fetch(dest, pe) &
        bind(C,name="shmem_int_fetch")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: dest
      integer(kind=C_INT), value :: pe
    end function shmem_int_fetch
  end interface

  interface
    integer(kind=C_LONG) function shmem_long_fetch(dest, pe) &
        bind(C,name="shmem_long_fetch")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: dest
      integer(kind=C_INT), value :: pe
    end function shmem_long_fetch
  end interface

  interface
    integer(kind=C_LONG_LONG) function shmem_longlong_fetch(dest, pe) &
        bind(C,name="shmem_longlong_fetch")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: dest
      integer(kind=C_INT), value :: pe
    end function shmem_longlong_fetch
  end interface

  interface
    real(kind=C_FLOAT) function shmem_float_fetch(dest, pe) &
        bind(C,name="shmem_float_fetch")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: dest
      integer(kind=C_INT), value :: pe
    end function shmem_float_fetch
  end interface

  interface
    real(kind=C_DOUBLE) function shmem_double_fetch(dest, pe) &
        bind(C,name="shmem_double_fetch")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: dest
      integer(kind=C_INT), value :: pe
    end function shmem_double_fetch
  end interface

  interface
    subroutine shmem_int_set(dest, value, pe) &
        bind(C,name="shmem_int_set")
      use, intrinsic :: iso_c_binding
      integer(kind=C_INT) :: dest
      integer(kind=C_INT), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_int_set
  end interface

  interface
    subroutine shmem_long_set(dest, value, pe) &
        bind(C,name="shmem_long_set")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG) :: dest
      integer(kind=C_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_long_set
  end interface

  interface
    subroutine shmem_longlong_set(dest, value, pe) &
        bind(C,name="shmem_longlong_set")
      use, intrinsic :: iso_c_binding
      integer(kind=C_LONG_LONG) :: dest
      integer(kind=C_LONG_LONG), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_longlong_set
  end interface

  interface
    subroutine shmem_float_set(dest, value, pe) &
        bind(C,name="shmem_float_set")
      use, intrinsic :: iso_c_binding
      real(kind=C_FLOAT) :: dest
      real(kind=C_FLOAT), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_float_set
  end interface

  interface
    subroutine shmem_double_set(dest, value, pe) &
        bind(C,name="shmem_double_set")
      use, intrinsic :: iso_c_binding
      real(kind=C_DOUBLE) :: dest
      real(kind=C_DOUBLE), value :: value
      integer(kind=C_INT), value :: pe
    end subroutine shmem_double_set
  end interface

end module shmem
